TASK: TRAIN_CNN

TRAINING:
    LEARNING_RATE: 1e-3
    EPOCH: 100
    DEVICE: cuda
    SCORE: accuracy
    WARMUP: 200
    PATIENCE: 5
    CHECKPOINT_PATH: saved_models
    JSON_PATH:
        TRAIN: data/train.json
        DEV:   data/dev.json
        TEST:  data/test.json

DATA:
    BATCH_SIZE: 16
    IN_CHANNEL: 3
    OUT_CHANNEL: 32
    KERNEL_SIZE: 3
    NUM_CLASSES: 2
    NUM_ITEMS: 24983
    IMAGE_FOLDER: data/images
    JSON_PATH:
        TRAIN: data/train.json
        DEV:   data/dev.json
        TEST:  data/test.json