TASK: TRAIN_CNN

TRAINING:
    LEARNING_RATE: 0.0001
    EPOCH: 100
    DEVICE: cuda
    SCORE: accuracy
    BATCH_SIZE: 32
    WARMUP: 200
    PATIENCE: 5
    CHECKPOINT_PATH: saved_models
    JSON_PATH:
        TRAIN: data/train.json
        DEV:   data/dev.json
        TEST:  data/test.json
MODEL:
    IN_CHANNEL: 3
    OUT_CHANNEL: 32
    KERNEL_SIZE: 3
    NUM_CLASSES: 2

DATA:
    NUM_ITEMS: 24983
    IMAGE_FOLDER: data/images
    JSON_PATH:
        TRAIN: data/train.json
        DEV:   data/dev.json
        TEST:  data/test.json